"""Record the audited operations in the later firmware helper modules."""
from pathlib import Path
import json,re
rows=[]
def add(old,new,detail):
    """Attach a current function location to one naming correction."""
    paths=[p for p in Path('src/rdx_core').glob('*.inc') if re.search(r'^\w[^\n]*\b'+re.escape(old)+r'\(',p.read_text(),re.M)]
    assert len(paths)==1,(old,paths)
    rows.append(dict(old=old,new=new,evidence=[f'{paths[0]}::{old}: {detail}']))
add('core_update_firmware_context_usb_transfer_state','core_notify_usb_disconnect','Sets speed to UNKNOWN=4, power state DISCONNECTED=3 and device state DEFAULT=0, then emits event 3. TI usb_chap9.h defines these enum values.')
add('core_process_firmware_context_endpoint_context','core_handle_usb_bus_reset','Sets device state to DEFAULT=1, cancels endpoint requests, clears USB address, and emits RESET event 2. TI USB_DEVICE_STATE_T distinguishes INITIAL=0 from DEFAULT=1.')
add('core_update_device_base_device_base_context','core_register_endpoint_callback','Appends a function pointer to the four-entry callback table at F6D0 and endpoint number without direction bit to F6E0.')
add('core_transfer_component_for_fallback_decoded_request','core_accumulate_response_byte_lanes','Adds each input byte into one of four independent byte lanes of the supplied checksum seed.')
add('core_transfer_component_for_flash_validation_context','core_accumulate_image_byte_lanes','Adds each input byte into one of four independent byte lanes of the supplied image checksum seed.')
add('core_transfer_reverse','core_compare_multiword_integers','Compares unsigned 32-bit words from the highest word down and returns 1, -1 or 0.')
add('core_update_configuration_update_context','core_get_configured_delay_ms','Reads one of four configured delays or default delay, then adds 5000 for slot zero while the processing timer is active.')
add('core_process_rti_clock_mhz','core_initialize_pwm_channel','Initializes timer channel registers GCR=1 and CTRL=0x12, programs PWM parameters, then clears the interrupt flag.')
add('core_update_flag_one_interrupt_transfer_context','core_allocate_software_timer','Allocates one of 19 countdown slots, clears its value and increments the allocation cursor.')
add('core_process_halt_forever_for_response_end_word','core_copy_bounded_response_field','Checks response length before copying the caller-selected reversed field bytes.')
add('core_process_ahci_port_control','core_reset_sata_link','Sets PxSCTL.DET=1, waits 5000 us and clears DET to initiate COMRESET.')
add('core_get_gpio_pin_context','core_enter_ata_standby','Issues STANDBY IMMEDIATE and clears the standby-related state on success; does not read a GPIO.')
add('core_update_device_update_context','core_is_adc_sample_above_threshold','Reads the selected MCP3008 channel and compares the low 16 bits against its indexed uint16 threshold.')
add('core_update_multiplier_multiplier','core_subtract_split_product','Subtracts value times a high/low 16-bit multiplier from a two-word accumulator, propagating borrow.')
add('core_is_supported_descriptor_opcode','core_is_scsi_write_opcode','Recognizes WRITE and WRITE AND VERIFY 6/10/12/16 opcode values 0A,2A,2E,8A,8E,AA,AE; see TI scsi.h.')
add('core_transfer_pending_ata_queue','core_reset_ata_callback_queue','Clears all 16 pending callback bytes and resets producer/consumer indices.')
add('core_get_ahci_control_register','core_start_ahci_command_override_if_stopped','Reads PxCMD.ST and sets PxCMD.CLO=0x10 only when ST is clear; returns the previous ST value.')
add('core_transfer_x01','core_decode_indexed_bytes','Subtracts the byte index and 0x54 from each encoded byte; used for embedded keys and prefixes.')
add('core_transfer_spi_transfer_storage','core_find_scsi_opcode_entry','Walks 42 entries with stride 0x18 from the cursor before the SCSI opcode table, matching the first byte.')
add('core_process_clear_memory_for_cartridge_monitor_context','core_initialize_cartridge_monitor','Clears 0x14 bytes and allocates its three timer IDs at offsets 0D,0E,0F.')
add('core_update_clear_memory_thermal_control_context','core_initialize_software_timers','Clears all 19 uint32 countdown slots and resets allocation count and elapsed ticks; not temperature control.')
add('core_update_firmware_context_usb_completion_state','core_notify_usb_suspend','Disables dynamic clock gating, sets USB power state SUSPENDED=1 and emits event 1; see TI USB_POWER_STATE_T.')
add('core_process_ti_memset_for_build_scsi_mode','core_initialize_scsi_response_buffer','Selects the response buffer, clears payload length bytes, publishes descriptor and sets allocated/used lengths.')
add('core_transfer_packed','core_format_hex_u32','Writes eight hexadecimal digits backwards from destination+8 and terminates the text with zero.')
add('core_process_halt_forever_for_build_scsi_mode','core_write_bounded_response_field','Checks the last requested byte index against response capacity before writing a reversed field value.')
add('core_process_ti_memset_0x20','core_reset_flash_validation_context','Clears 0x198 bytes, invokes reset hook, and preserves the boolean at offset 0x20.')
add('core_update_spi_transfer_context_for_program_spi_flash','core_unmask_mww_interrupt_when_allowed','Writes VIM_REQMASKSET0 bit21 when the MWW interrupt suspension flag permits or caller overrides.')
add('core_update_mww_saved_request','core_reset_bot_command_state','Clears saved CBW state and BOT phase flags, then receives a 0x1f-byte CBW on endpoint 3.')
add('core_submit_fixed_ata_command','core_submit_ata_identify_device','Builds the taskfile and issues ATA opcode EC with ahci_execute_taskfile_command.')
add('core_update_ti_memset_for_ti_memset_for','core_clear_media_record_state','Clears context subregions 0x10..0x43 and 0x44..0x7B without altering other fields.')
add('core_forward_ti_memset','core_clear_media_record_state_after_transfer','Clears context subregions 0x10..0x43 and 0x44..0x7B after transfer completion.')
add('core_process_persistent_identity_record_for_identity_persistence_context','core_save_persistent_state_with_checksum','Updates the 0x40-byte persistent-state checksum and writes the primary flash copy.')
add('core_update_sense_refresh_context','core_clear_primary_secondary_sector_offsets','Clears both low/high word pairs used for sector offsets; no sense response is constructed here.')
add('core_update_cddis_reg_off_cartridge_eject_control','core_enable_processor_sleep_clock_gating','Writes CDDIS=3 when USB core revision exceeds 0x101A. TI system.h maps bits 0 and 1 to GCLK/HCLK sleep gating.')
add('core_get_mww_active_flag','core_is_usb_endpoint_stalled','Selects EP0 OUT/IN stalled-field origin by direction bit7 and indexes the EP_INFO_T stride of 0x28.')
add('core_handle_type_type','core_handle_scsi_security_protocol','Dispatches opcodes A2/B5 (SECURITY PROTOCOL IN/OUT), validates protocol ID and protocol-specific fields, and routes management records.')
add('core_get_command_feature','core_scsi_write_requests_fua','Tests FUA bit3 for WRITE(10), WRITE(16), and WRITE(12), opcodes 2A,8A,AA.')
add('core_update_set_interrupt_mmio','core_erase_boot_flash_sectors','Calls the SPI sector erase helper for sixteen 0x1000-byte sectors beginning at zero, stopping on error.')
add('core_get_cartridge_eject_control','core_usb_revision_supports_new_link_requests','Returns whether USB core revision is greater than 0x1089; this capability gates USB link-state handling, not eject control.')
add('core_get_ahci_status_register','core_get_sata_link_speed','Extracts PxSSTS bits 7:4 (SPD), not an entire status register.')
add('core_copy_words_to_interleaved_destination','core_copy_bytes_to_alternate_positions','Writes one byte from each source position into every second destination byte; it does not copy words.')
add('core_update_ti_memset_for_lookup_arguments','core_initialize_media_record','Clears 0x84-byte media record and stores context pointer at offset 0x0C.')
add('core_update_command_phase_flags_for_firmware_context_byte','core_clear_command_phase_flags','Clears the selected flag mask via flags AND NOT mask.')
add('core_update_command_phase_flags_for_command_phase','core_set_command_phase_flags','Sets the selected flag mask via flags OR mask.')
add('core_get_thermal_control_context','core_is_software_timer_expired','Reads a countdown slot indexed by the supplied timer ID and tests for zero.')
add('core_update_command_status_update','core_set_usb_device_address','Writes the seven-bit USB address into DCFG bits9:3 using mask 0x3F8.')
add('core_update_ti_memset_for_ti_memset','core_initialize_ata_taskfile','Clears eleven taskfile bytes and sets device byte at offset9 to LBA mode 0x40.')
add('core_update_ahci_device_context','core_set_ahci_callbacks','Stores completion, DMA Setup FIS and error callback addresses.')
add('core_set_transfer_interrupt_enable_mask','core_mask_mww_interrupt','Writes VIM_REQMASKCLR0 bit21, masking the MWW interrupt; previous name implied enabling it.')
add('core_update_usb_reset_state','core_request_usb_link_state','Writes DCTL.ULSTCHNGREQ bits4:1 with mask0x1E; not a USB reset-state field.')
add('core_update_clear_memory_response_buffer_context','core_clear_selected_sense_fields','Clears four bytes holding sense key and additional sense code/qualifier.')
add('core_update_clear_memory_usb_event_counter','core_clear_usb_event_counters','Clears the five uint32 USB event counters at the counter origin.')
add('core_get_response_byte_context','core_get_unit_serial_number','Returns the fixed unit serial number buffer.')
add('core_update_secondary_update_context','core_decode_word_cipher_delta','Decodes four embedded bytes into the TEA-family round delta 0x9E3779B9.')
add('core_set_SYSECR_REG_OFF_to_hex_8000_handler','core_request_system_reset','Writes software-reset value 0x8000 to SYSECR.')
add('core_set_CDDIS_REG_OFF_to_hex_38_handler','core_disable_bus_dynamic_clock_gating','Writes CDDIS=0x38; TI system.h maps bits3:5 to M3 RAM/ROM, BMM2 and AHB/VBUS dynamic gating.')
add('core_update_spi_update_spi','core_wait_spi_transmit_empty','Waits for SPI status flag0x200 (TX empty).')
add('core_get_resource_ahci_state','core_get_primary_sata_link_speed','Returns link speed read from SATA port zero.')
add('core_get_constant_hex_1014_value','core_get_scsi_response_buffer_capacity','Returns 0x1014, the SCSI response buffer capacity defined by SCSI_RESPONSE_BUFF_SIZE.')
add('core_get_constant_hex_1000_value','core_get_transfer_buffer_capacity','Returns 0x1000, the normal transfer buffer capacity.')
add('core_forward_interrupt_transfer_context','core_advance_software_timers','Saturating-subtracts elapsed ticks from each of nineteen software timers and advances elapsed-time counter.')
add('core_forward_end_remaining','core_copy_bytes','Copies aligned words where possible, then trailing bytes. Direction is forward and length is measured in bytes.')
add('core_forward_reconnect_state','core_service_usb_reconnect','Services delay states, disconnects USB, waits1000 ms, then reconnects and starts the post-connect timer.')
Path('temp/naming-audit/late-function-renames.json').write_text(json.dumps(rows,indent=2)+'\n')
print('Audited function corrections',len(rows))
