"""Record reviewed branch and callback names without changing firmware files."""
import json
from pathlib import Path

reviews = {
54: ('core_spi_flash_begin_write_transaction', 'src/rdx_core/04_hash_flash_usb_thermal.inc:554-571,602-603: operation codes 2 and 10 join before status polling, address/opcode submission, and byte writes; the final byte clears the continuation bit.', 'structural'),
55: ('core_spi_flash_return_transfer_result', 'src/rdx_core/04_hash_flash_usb_thermal.inc:614-615: normal completion and read/write/setup errors return CONCAT44(condition_2_field, operation_status).', 'structural'),
56: (None, 'src/rdx_core/04_hash_flash_usb_thermal.inc:750-754,789-810: ramp-entry and downward-step paths join at the selected PWM duty update.', 'structural'),
57: ('core_thermal_pwm_arm_ramp_timer', 'src/rdx_core/04_hash_flash_usb_thermal.inc:775-777,814-819: selected intervals of 60000 or 5000 arm the same ramp timer.', 'structural'),
58: (None, 'src/rdx_core/04_hash_flash_usb_thermal.inc:721-729,779-780: idle and stop-ramp paths set PWM duty to zero, clear ramp state, and return.', 'structural'),
59: (None, 'src/rdx_core/05_device_descriptor_dispatch.inc:130-143: both detected drive selections set core_mechanism_alternate_output_active to 1 before output activation.', 'structural'),
60: ('core_mechanism_apply_selected_output_pwm', 'src/rdx_core/05_device_descriptor_dispatch.inc:100-115,130-143: the selected logical output 0x0c or 0x0d receives core_apply_pwm_percentage(output,100,0x32), followed by the shared delay.', 'structural'),
61: (None, 'src/rdx_core/05_device_descriptor_dispatch.inc:110-114,122-124: PWM and reset-output paths select 2000 for the shared mechanism timer.', 'structural'),
62: (None, 'src/rdx_core/05_device_descriptor_dispatch.inc:96-98,113-115: intervals selected by each mechanism path arm core_command_completion_context.', 'structural'),
63: (None, 'src/rdx_core/05_device_descriptor_dispatch.inc:100-104: disables logical output 10, waits 0x32 microseconds, and clears the alternate-output active flag.', 'structural'),
64: ('core_descriptor_lookup_release_temporary_record', 'src/rdx_core/05_device_descriptor_dispatch.inc:217-234: successful lookup and post-allocation failures converge on core_reset_output_record(working_buffer), then return their existing result.', 'structural'),
65: ('core_descriptor_dispatch_finalize_payload', 'src/rdx_core/19_identity_sense_and_mww.inc:787-795: successful descriptor handlers update the payload at offset+0x0c when present and return zero.', 'structural'),
66: ('core_scsi_cdb_reject_unsupported_opcode', 'src/rdx_core/05_device_descriptor_dispatch.inc:482-506: unsupported opcodes assign buffer[3]=7 and status_bits=7, bypass LBA/length decoding, and take the failure-return path.', 'structural'),
67: ('core_scsi_cdb_select_sixteen_byte_layout', 'src/rdx_core/05_device_descriptor_dispatch.inc:482-509: opcodes 0x88,0x8a,0x8e,0x8f select offset-table index 3, multiplied by 4 before SCSI LBA and transfer-length decoding.', 'structural'),
68: ('core_scsi_cdb_return_decode_success', 'src/rdx_core/05_device_descriptor_dispatch.inc:502-504,531-534: both unsupported-opcode and decoded paths return status_bits == 0.', 'structural'),
69: ('core_response_descriptor_release_temporary_record', 'src/rdx_core/05_device_descriptor_dispatch.inc:578-592: completed response construction and range failures release data_cursor through core_reset_output_record before returning their status.', 'structural'),
70: ('core_record_transfer_build_result_descriptor', 'src/rdx_core/05_device_descriptor_dispatch.inc:625-630,667-674: an existing matching descriptor and a newly submitted transfer converge on construction of the result descriptor. src/rdx_core/08_thermal_and_record_validation.inc:482-512 writes type, offset, and length fields and validates combined bounds.', 'structural'),
71: ('core_usb_control_transfer_finalize_error_state', 'src/rdx_core/05_device_descriptor_dispatch.inc:809-823: shared completion checks state 5, ends transfers for endpoints 0 and 0x80, and invokes endpoint-zero cleanup. src/rdx_core/13_runtime_transfer_helpers.inc:671-698 shows the endpoint helper submits command 0x908 and clears an active resource before polling.', 'structural'),
72: ('core_write_buffer_select_invalid_field_status', 'src/rdx_core/06_record_transfer_helpers.inc:135-166: unsupported mode, failed buffer load, or missing response state selects status 8. This target does not set the transfer-ready flag.', 'structural'),
73: (None, 'src/rdx_core/06_record_transfer_helpers.inc:168-174: stores the selected completion status into *buffer before the response hook.', 'structural'),
74: (None, 'src/rdx_core/06_record_transfer_helpers.inc:149,165,171-174: paths preserving a preexisting result and paths storing a fresh result share the final response hook and return.', 'structural'),
75: ('core_write_buffer_return_validation_failure', 'src/rdx_core/06_record_transfer_helpers.inc:119-129: oversized payload selects 8 and failed validation selects 0x1f; both store *buffer and return before command execution.', 'structural'),
76: ('core_command_dispatch_store_phase_rejection', 'src/rdx_core/06_record_transfer_helpers.inc:283-302: phase gates select 0x0d or 0x0e, store that rejection in *buffer, then select phase 3 and update auxiliary status.', 'structural'),
77: ('core_command_dispatch_validate_cdb_fields', 'src/rdx_core/06_record_transfer_helpers.inc:246-266: loops over request bytes after the opcode, masks permitted bits using the command entry, rejects remaining bits with status 8, and invokes the allowed command callback.', 'structural'),
78: ('core_command_dispatch_store_lookup_or_field_error', 'src/rdx_core/06_record_transfer_helpers.inc:237-259: failed opcode lookup selects 7; forbidden request bits select 8; this target stores the chosen error and skips directly to auxiliary status update.', 'structural'),
79: ('core_command_dispatch_commit_auxiliary_status', 'src/rdx_core/06_record_transfer_helpers.inc:244,266,298-303: callback, lookup-error, field-error, and phase-update paths commit *buffer through core_update_command_phase_auxiliary.', 'structural'),
80: ('core_descriptor_request_check_runtime_eligibility', 'src/rdx_core/06_record_transfer_helpers.inc:342-362: the zero-flag path checks runtime context+0x2c and selects status 0x14 if rejected. src/rdx_core/17_cartridge_state_and_validation.inc:409-424 checks field+0x44, state byte+0x12, and allowed bits at +0x24/+0x74; a more specific access-mode claim is not established.', 'structural'),
81: (None, 'src/rdx_core/06_record_transfer_helpers.inc:368-382: all selected validation failures and success status converge on storing *buffer.', 'structural'),
82: (None, 'src/rdx_core/06_record_transfer_helpers.inc:343-345,378-382: paths retaining an earlier buffer status and paths writing a fresh status return operation_status == 0.', 'structural'),
83: ('core_image_compatibility_add_signature_bit', 'src/rdx_core/06_record_transfer_helpers.inc:475-503: R2CG, R2iG, and R2EF signatures select an additional bit code from 0x36 through 0x38 before the compatibility query. src/rdx_core/16_record_builders_and_capacity.inc:811-829 implements the bitwise OR operation.', 'structural'),
84: ('core_image_compatibility_check_requested_code', 'src/rdx_core/06_record_transfer_helpers.inc:482-503: recognized signatures converge on core_process_command_code_in(&context_derived,context). src/rdx_core/16_record_builders_and_capacity.inc:557-582 queries a translated code bit in a sixteen-byte set.', 'structural'),
85: ('core_image_compatibility_return_match_result', 'src/rdx_core/06_record_transfer_helpers.inc:486-508: a matching compatibility bit preserves success_flag=1; unrecognized or nonmatching paths set zero; both return the original record context with that flag.', 'structural'),
86: (None, 'src/rdx_core/06_record_transfer_helpers.inc:475 compares four bytes against this address. Firmware payload bytes at 0x08004fa0 are 52 32 43 47, the ASCII signature R2CG.', 'confirmed'),
87: (None, 'src/rdx_core/06_record_transfer_helpers.inc:490 compares four bytes against this address. Firmware payload bytes at 0x08004fa8 are 52 32 69 47, the ASCII signature R2iG; the lowercase identifier spelling remains suitable.', 'confirmed'),
88: ('core_metadata_response_release_temporary_record', 'src/rdx_core/07_eject_reconnect_smart.inc:39-54: completed metadata response and lookup failures release data_cursor through core_reset_output_record before returning the selected result.', 'structural'),
89: ('core_cartridge_monitor_arm_selected_timer', 'src/rdx_core/07_eject_reconnect_smart.inc:129-162: thermal or response timing paths select data_cursor; the shared target arms it with 1000 or 300000 according to standby and accumulated-offset handling.', 'structural'),
90: ('core_word_bit_scan_initialize_result', 'src/rdx_core/07_eject_reconnect_smart.inc:194-227: the highest-set-bit search and word-boundary path join at core_copy_word_buffer(context,value,condition), before traversing the remaining bits. No specific arithmetic algorithm is required by the proposed name.', 'structural'),
91: ('core_reconnect_arm_timer_and_commit_state', 'src/rdx_core/07_eject_reconnect_smart.inc:273-301 and src/rdx_core/24_reconnect_state_machine.inc:47-75: the selected 1 or 1000 delay arms the reconnect timer before next_state is committed.', 'structural'),
92: ('core_read_buffer_reject_invalid_request', 'src/rdx_core/07_eject_reconnect_smart.inc:320-345: unsupported buffer mode or identifier combinations converge on *buffer=8 and return, bypassing response allocation.', 'structural'),
93: ('core_paired_descriptor_return_result', 'src/rdx_core/07_eject_reconnect_smart.inc:466-492: initial descriptor-request failure and completed paired-field states share CONCAT44(result_context,operation_status). The target returns rather than executing the component helper.', 'structural'),
94: ('core_usb_endpoint_select_transfer_direction', 'src/rdx_core/07_eject_reconnect_smart.inc:616-631: revision-dependent configuration selection converges on bit7 direction testing, recording the length in the OUT context or continuing to IN flags and context.', 'structural'),
95: ('core_usb_endpoint_submit_configuration', 'src/rdx_core/07_eject_reconnect_smart.inc:621-636: both direction paths submit endpoint command 1 with the assembled parameters, then update the endpoint completion mode.', 'structural'),
96: ('core_cartridge_monitor_store_sequence_status', 'src/rdx_core/08_thermal_and_record_validation.inc:56-101: timeout, follow-up, and next-sequence paths choose status 0,4,7 and store it in *buffer before returning.', 'structural'),
97: ('core_output_sequence_store_state_and_flag', 'src/rdx_core/08_thermal_and_record_validation.inc:331-347: state 9 writes the caller output and sets the flag; state 2 writes state_record=3 and clears the flag; both return 1. buffer_cursor can address either record, so the name avoids asserting only a response-buffer write.', 'structural'),
98: ('core_output_sequence_store_output_state', 'src/rdx_core/08_thermal_and_record_validation.inc:318-323,349-355: states 8/10 choose output state 1 while state 1 initializes the sequence and chooses output state 0; both store *buffer.', 'structural'),
99: ('core_record_transfer_validate_result_bounds', 'src/rdx_core/08_thermal_and_record_validation.inc:492-516: successful descriptor setup and selected lookup errors share combined-record bounds validation; a bounds failure overrides the result with status 4.', 'structural'),
100: (None, 'src/rdx_core/08_thermal_and_record_validation.inc:624-644: selected SPI status-bit conditions set condition_met=true and leave the polling loop through the common end-transfer path.', 'structural'),
101: (None, 'src/rdx_core/08_thermal_and_record_validation.inc:636-645: success, SPI error, and timeout close the SPI transaction with 0x60000 and return the selected status.', 'structural'),
102: ('core_feature_command_return_rejection_status', 'src/rdx_core/08_thermal_and_record_validation.inc:715-733: unavailable command phase selects 2 and an active feature conflict selects 0x0b; both store *buffer and return.', 'structural'),
103: ('core_record_append_check_complete_capacity', 'src/rdx_core/09_command_phase_and_ata.inc:274-291: full and truncated available lengths converge on the equality requiring the complete four-byte header plus payload; only a full record is written.', 'structural'),
104: ('core_record_append_return_next_offset', 'src/rdx_core/09_command_phase_and_ata.inc:291-297: successful append uses output_length while insufficient space uses zero; both return (output_length+record_offset)&0xffff.', 'structural'),
105: (None, 'src/rdx_core/09_command_phase_and_ata.inc:512-528: elapsed phase 4 and phase 2 arm the one-second timer and select phase 3.', 'structural'),
106: (None, 'src/rdx_core/09_command_phase_and_ata.inc:518-528: phase selections 5 and 3 converge on buffer[2] assignment.', 'structural'),
107: (None, 'src/rdx_core/09_command_phase_and_ata.inc:507-510,530-535: ordinary and unavailable-monitor paths reset follow-up intervals to 5000 and 60000 before returning their result.', 'structural'),
108: ('core_callback_sequence_commit_next_state', 'src/rdx_core/10_spi_flash_and_response_dispatch.inc:475-520: state transitions 8->9,9->10,10->1,1->2 and 3/7->8 converge on the state-field write; the separate state-6 callback path returns before this label.', 'structural'),
109: ('core_cartridge_link_arm_retry_timer', 'src/rdx_core/11_usb_ata_payload_transfer.inc:262-279: entry state selects retry count zero, retry state increments it, and both derive the interval and arm core_cartridge_ready_retry_timer.', 'structural'),
110: ('core_usb_descriptor_return_matching_entry', 'src/rdx_core/11_usb_ata_payload_transfer.inc:378-389: a matching descriptor or HID report entry stores the selected pointer through length_output when nonnull and returns success zero.', 'structural'),
111: ('core_payload_lookup_return_failure', 'src/rdx_core/11_usb_ata_payload_transfer.inc:695-710: parse failure, offset overrun, insufficient payload, and record bounds failures force the result to zero. The target is a failure path, not an unconditional return.', 'structural'),
112: ('core_bounded_word_write_emit_available_bytes', 'src/rdx_core/13_runtime_transfer_helpers.inc:465-489: after clamping to available space and at most four bytes, writes low-order bytes while shifting right, then advances the offset tracker by the actual count; zero-byte paths still join.', 'structural'),
113: ('core_output_cycle_select_inactive_flag', 'src/rdx_core/13_runtime_transfer_helpers.inc:554-574: cycle transitions 0->3 and 1->2 select flag zero before committing the state and flag; the other transitions select flag one.', 'structural'),
114: ('core_output_cycle_apply_logical_outputs', 'src/rdx_core/13_runtime_transfer_helpers.inc:550-578: default-sequence, ordinary cycle, and unsupported-state paths converge on applying the logical output pair through core_update_spi_set_logical_for_x01_for_resource.', 'structural'),
115: ('core_mww_request_mark_terminal_state', 'src/rdx_core/14_mww_usb_command_control.inc:417-438: an empty source descriptor or decode status 5 selects saved-request state 3. Other paths select states 1 or 2; no more specific completion meaning is established.', 'structural'),
116: ('core_logical_output_pair_apply_second_output', 'src/rdx_core/15_control_transfer_crc_records.inc:819-835: branches set the first output and select working_result 0 or 1; the shared target applies that value to buffer[4], the second logical output.', 'structural'),
117: (None, 'src/rdx_core/11_usb_ata_payload_transfer.inc:306-313: copies a fixed 0x80-byte operand into destination_record+5 beside the caller operand at +0x25, then transforms both through the same helper; the retained neutral operand-template name avoids an unverified cryptographic classification.', 'structural'),
118: (None, 'src/rdx_core/14_mww_usb_command_control.inc:321-329: command status is multiplied by three and the byte at this base populates fixed-format sense byte 2. Firmware bytes at 0x0800e6b4 begin 00 00 00 00 00 00 02 3a 00.', 'confirmed'),
119: (None, 'src/rdx_core/14_mww_usb_command_control.inc:323-329: command status times three indexes base 0x0800e6b6 and fills fixed-format sense byte 0x0d, the additional sense qualifier.', 'confirmed'),
120: (None, 'src/rdx_core/03_identity_and_mechanism.inc:33: copies eight bytes into the default secondary identity response. Firmware bytes at 0x0800e760 are ASCII TANDBERG.', 'confirmed'),
}
label_reviews = {
1: ('usb_bot_in_transfer_complete_callback_entry', 'src/usb_stack.c:221-227 registers this entry for channel 0x83 and initializes CBW/CSW-related descriptors. TI_Reference_Source/TUSB9261FW_SourceCode/source/ums_bot.c:1180-1202,1325-1341 identifies the corresponding endpoint-IN callback as BOT data-transfer completion, registered during ums_bot_init.', 'confirmed'),
2: (None, 'src/ahci.c:326-329 registers this entry through core_register_usb_event_callback during AHCI initialization; the existing device-event callback role remains supported. Firmware bytes at 0x08007fb8 begin an executable register-saving prologue.', 'structural'),
3: (None, 'src/rdx_core/14_mww_usb_command_control.inc:43-46 installs this callback through core_update_ahci_device_context when restoring default AHCI request handling. Firmware bytes at 0x080098a4 begin executable instructions; no name change is required.', 'structural'),
4: ('usb_stack_data_transfer_callback_entry', 'src/scsi.c:38 passes this as usb_hal_init argument two; src/usb_stack.c:68 stores it in usb_secondary_state_callback, invoked with transfer arguments at src/rdx_core/11_usb_ata_payload_transfer.inc:789. TI_Reference_Source/TUSB9261FW_SourceCode/source/usb_hal.c:1818-1826 names that argument pDataXferCallback.', 'confirmed'),
5: ('usb_set_sel_data_complete_callback_entry', 'src/rdx_core/10_spi_flash_and_response_dispatch.inc:662-672 installs this callback while servicing request 0x30 on the SuperSpeed path and schedules EP0 OUT data. TI_Reference_Source/TUSB9261FW_SourceCode/source/usb_chap9.c:2061-2065,2083-2095 identifies the matching SET SEL data callback and its U2PEL update.', 'confirmed'),
6: (None, 'src/rdx_core/13_runtime_transfer_helpers.inc:209 supplies this executable entry with logical pin configuration index 3. Keep the existing limited role: the current gio.c helper has incomplete callback argument propagation, so the exact physical event and callback behavior are not asserted.', 'structural'),
7: (None, 'src/rdx_core/14_mww_usb_command_control.inc:328 indexes this base with status*3 for sense byte 0x0c. It intentionally remains neutral because its fixed address 0x0800e6b4 aliases the sense-key table rather than a separate +1 additional-sense-code base; naming work must not alter that binding.', 'structural'),
}
rows=[]
for item in json.loads(Path('temp/naming-audit/late-control-flow-input.json').read_text()):
    index=int(item['placeholder_name'].rsplit('_',1)[1])
    review=(label_reviews if item['placeholder_name'].startswith('firmware_label_data_') else reviews)[index]
    name,evidence,confidence=review
    rows.append({'old':item['semantic_name'],'new':name or item['semantic_name'],'address':item['address'],'evidence':evidence,'confidence':confidence})
assert len(rows)==74
assert len({row['old'] for row in rows})==len(rows)
assert len({row['new'] for row in rows})==len(rows)
Path('temp/naming-audit/late-control-flow-renames.json').write_text(json.dumps(rows,indent=2)+'\n')
print(json.dumps({'audited':len(rows),'renamed':sum(row['old']!=row['new'] for row in rows),'retained':sum(row['old']==row['new'] for row in rows)}))
