; SPDX-FileCopyrightText: 2026 Andre Fiedler
;
; SPDX-License-Identifier: AGPL-3.0-or-later

[platformio]
default_envs = tusb9261_ti_cgt
src_dir = src
include_dir = include

[env:tusb9261_ti_cgt]
platform = platformio/native@1.2.1
build_src_filter = -<*>
extra_scripts = pre:scripts/ti_cgt_build.py
custom_ti_cgt_root = C:\ti\ti-cgt-arm_5.2.5
custom_ti_cgt_root_macos = ~/ti/ti-cgt-arm_5.2.9
