/*
 * SPDX-FileCopyrightText: 2009 Texas Instruments Incorporated
 * SPDX-FileCopyrightText: 2026 André Fiedler
 *
 * SPDX-License-Identifier: LicenseRef-TI-TUSB926x AND AGPL-3.0-or-later
 */

//=======================================================================================
// Filename    : mww.h
//             
// Project     : TUSB926x Firmware.
//             
// Description : Header file for memory wrap window.
// 
//   (C) Copyright 2009 by Texas Instruments Incorporated.
//   All rights reserved.
//
// Revision History:
//   MM/DD/YY
//   04/20/09 - Brian Quach - Creation.
//
//=======================================================================================


/*! @file
 * 
 * Header file for the Memory Wrap Window.
 * 
 */

#ifndef _MWW_H_
#define _MWW_H_

#include "tusb9260_types.h"

/*----------------------------------------------------------------------------+
| Macros                                                                      |
+----------------------------------------------------------------------------*/

#define SATA_TO_USB_WRAP_WINDOW_NUM  0 
#define USB_TO_SATA_WRAP_WINDOW_NUM  1

#define MWW_BLK_SIZE_1KB   0x0       
#define MWW_BLK_SIZE_2KB   0x1       
#define MWW_BLK_SIZE_4KB   0x2       
#define MWW_BLK_SIZE_8KB   0x3       
#define MWW_BLK_SIZE_16KB  0x4       
#define MWW_BLK_SIZE_32KB  0x5
#define MWW_BLK_SIZE_64KB  0x6       

#define MWW_1KB_BLK_ADDR_OVERFLOW_MASK   0x0003F800 /* bits [17:11] for the address decode */
#define MWW_2KB_BLK_ADDR_OVERFLOW_MASK   0x0003F000 /* bits [17:12] for the address decode */
#define MWW_4KB_BLK_ADDR_OVERFLOW_MASK   0x0003E000 /* bits [17:13] for the address decode */
#define MWW_8KB_BLK_ADDR_OVERFLOW_MASK   0x0003C000 /* bits [17:14] for the address decode */
#define MWW_16KB_BLK_ADDR_OVERFLOW_MASK  0x00038000 /* bits [17:15] for the address decode */
#define MWW_32KB_BLK_ADDR_OVERFLOW_MASK  0x00030000 /* bits [17:16] for the address decode */
#define MWW_64KB_BLK_ADDR_OVERFLOW_MASK  0x00020000 /* bit 17 for the address decode */

#define MWW_WINDOW_DECODE_MASK      0x001C0000 /* bits [20:18] */

/* Offset from datapath RAM start addr must be aligned to block size */
#define WRAP_WINDOW_BLOCK_SIZE          MWW_BLK_SIZE_32KB
#define WRAP_WINDOW_ADDR_OVERFLOW_MASK  MWW_32KB_BLK_ADDR_OVERFLOW_MASK    /* must match block size */
#define WRAP_WINDOW_BLOCK_SIZE_BYTES    (32 * 1024)
#define SATA_TO_USB_WRAP_WINDOW_OFFSET  0
#define USB_TO_SATA_WRAP_WINDOW_OFFSET  0x8000  /* 32 KB */   


/* Datapath RAM wrap window registers */
#define MWWxBLKOFFSET(window_num)      (0xFD000000 + (window_num * 0x10))
#define MWWxBLKSIZE(window_num)        (0xFD000004 + (window_num * 0x10))
#define MWWxWRTOFFSET(window_num)      (0xFD000008 + (window_num * 0x10))
#define MWWxRDOFFSET(window_num)       (0xFD00000C + (window_num * 0x10))


#define MWW_STATUS_REG_OFF             0xFD000040
#define MWW_CONTROL_REG_OFF            0xFD000044
#define MWW_USB_MASTER_ADDR_REG_OFF    0xFD000048
#define MWW_SATA_MASTER_ADDR_REG_OFF   0xFD00004C


#define MWW_STATUS_USB_AHB_RDY_BIT    0x00000010
#define MWW_STATUS_SATA_AHB_RDY_BIT   0x00000020
#define MWW_STATUS_WIN0_EMPTY_BIT     0x00001000
#define MWW_STATUS_WIN1_EMPTY_BIT     0x00002000
#define MWW_STATUS_WIN2_EMPTY_BIT     0x00004000
#define MWW_STATUS_WIN3_EMPTY_BIT     0x00008000

#define MWW0_ADDR  0xC0100000
#define MWW1_ADDR  0xC0140000
#define MWW2_ADDR  0xC0180000
#define MWW3_ADDR  0xC01C0000

#define MWW_BASE_ADDRESS 0xC0100000
#define MWWxADDR(window_num)    (MWW_BASE_ADDRESS + (window_num * 0x40000))

#define MWW_VIRTUAL_WINDOW_SIZE  0x0003E000  /* 248KB for all windows (using window size of 256 KB causes problems) */

#define MWW_BLK_SIZE_DIRECTION_BIT  0x80000000
#define MWW_DIR_USB_TO_SATA         0x80000000
#define MWW_DIR_SATA_TO_USB         0x0

/*----------------------------------------------------------------------------+
| Function Prototypes                                                         |
+----------------------------------------------------------------------------*/

void mww_init(void);
void mww_error_isr(void);
void mww_reset_rw_offsets(void);
BOOLEAN_T mww_check_usb_interface_ready(void);
BOOLEAN_T mww_check_sata_interface_ready(void);

void mww_force_sata_interface_ready(void);


#if 0  /* Do not use this function.  USB core cannot handle AHB error generated by forcing windows ready. */
void mww_force_usb_interface_ready(void);
#endif

#if DEBUG_LEVEL >= 1
void mww_print_debug_info(void);
#endif


void mww_init_read_only(void);
void mww_init_write_only(void);


#endif /*_MWW_H_*/
